CREATE TABLE CIRCUITO (
NOMBRE VARCHAR2(20),
WEB VARCHAR2(50),
AÑO NUMBER(4),
VEL_MAX NUMBER(5,2),
CURVAS NUMBER(3),
LONGITUD NUMBER(5,2));

CREATE TABLE ESCUDERIA (
NOMBRE VARCHAR2(20) PRIMARY KEY,
JEFE VARCHAR2(30),
DIRECTOR VARCHAR2(30));


CREATE TABLE PILOTO (
NOMBRE VARCHAR2(30) CONSTRAINT PK_PILOTO PRIMARY KEY,
NOMBRE_ESCUDERIA VARCHAR2(20)REFERENCES ESCUDERIA,
FECHA_NAC DATE,
DORSAL NUMBER(2),
PUNTOS NUMBER(2));