CREATE TABLE COMPAÑIA (
CIF VARCHAR2(12),
NOMBRE VARCHAR2(30) UNIQUE,
ESLOGAN VARCHAR2(30),
CONSTRAINT PK_COMPAÑIA PRIMARY KEY(CIF));

ALTER TABLE CIRCUITO ADD CONSTRAINT PK_CIRCUITO PRIMARY KEY (NOMBRE);

CREATE TABLE CARRERA (
FECHA DATE CONSTRAINT PK_CARRERA PRIMARY KEY,
NOMBRECIRCUITO VARCHAR2(20) CONSTRAINT FK_CIRCUITO REFERENCES CIRCUITO);

CREATE TABLE CORRE (
NOMBREPILOTO VARCHAR2(30) CONSTRAINT FK_PILOTO REFERENCES PILOTO NOT NULL,
FECHA_CARRERA DATE NOT NULL CONSTRAINT FK_CARRERA REFERENCES CARRERA,
POS_INICIAL NUMBER(2) NOT NULL CHECK (POS_INICIAL >0),
POS_FINAL NUMBER(2) NOT NULL CHECK(POS_FINAL>0),
CONSTRAINT PK_CORRE PRIMARY KEY (NOMBREPILOTO,FECHA_CARRERA));

CREATE TABLE PATROCINA (
NOMBREPILOTO VARCHAR2(30) CONSTRAINT FK_PILOTO_PATROCINA REFERENCES PILOTO,
CIFCOMPAÑIA VARCHAR2(12) CONSTRAINT FK_COMPAÑIA REFERENCES COMPAÑIA,
CONSTRAINT PK_PATROCINA PRIMARY KEY (NOMBREPILOTO, CIFCOMPAÑIA));

ALTER TABLE CORRE ADD TIEMPO NUMBER(5,2) DEFAULT 0;

ALTER TABLE PATROCINA ADD CONTRATO NUMBER(5)
CHECK (CONTRATO > 1000 AND CONTRATO < 100000);

ALTER TABLE PATROCINA DROP CONSTRAINT SYS_C007009;

ALTER TABLE PATROCINA ADD CONSTRAINT CHEQUEAR_CONTRATO
CHECK (CONTRATO >10000 AND CONTRATO <100000);


















