CREATE OR REPLACE VIEW VISTA3
AS SELECT COUNTRY_ID, COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES JOIN REGIONS USING(REGION_ID);
    
SELECT * FROM VISTA3;   


INSERT INTO VISTA3 VALUES ('AA','AAAAAA', 'asia');

UPDATE VISTA3 SET REGION_NAME='europe' WHERE COUNTRY_ID='AA';
UPDATE VISTA3 SET COUNTRY_NAME='BBBBBB' WHERE COUNTRY_ID='AA';
DELETE FROM VISTA3 WHERE COUNTRY_NAME='BBBBBB';
DELETE FROM VISTA3 WHERE COUNTRY_ID='AB';





CREATE OR REPLACE TRIGGER T10
INSTEAD OF INSERT OR UPDATE OR DELETE ON VISTA3 FOR EACH ROW
DECLARE
    REGION_COD REGIONS.REGION_ID%TYPE;
BEGIN
    IF INSERTING THEN 
        SELECT REGION_ID INTO REGION_COD
        FROM REGIONS
        WHERE REGION_NAME=:NEW.REGION_NAME;
        
        INSERT INTO COUNTRIES VALUES (:NEW.COUNTRY_ID, :NEW.COUNTRY_NAME, REGION_COD);
    
      ELSE IF UPDATING THEN
                SELECT REGION_ID INTO REGION_COD
                  FROM REGIONS
                  WHERE REGION_NAME=:NEW.REGION_NAME;
            
                UPDATE COUNTRIES 
                SET COUNTRY_NAME= :NEW.COUNTRY_NAME, REGION_ID=REGION_COD
                WHERE COUNTRY_ID=:NEW.COUNTRY_ID;
            
            ELSE
            
                 DELETE FROM COUNTRIES
                 WHERE COUNTRY_ID= :OLD.COUNTRY_ID
                        OR COUNTRY_NAME=:OLD.COUNTRY_NAME;
            
            END IF;

      END IF;
END;      
        
        
        
        
        
        
        
        
        
         




















