CREATE DATABASE IF NOT EXISTS BDDEP;

USE BDDEP;

CREATE TABLE IF NOT EXISTS Modulos (id int NOT NULL,nombre varchar(20) NOT NULL UNIQUE, siglas varchar (5) NOT NULL, PRIMARY KEY (id));


CREATE TABLE IF NOT EXISTS Alumnos (id int NOT NULL, nombre varchar(20) NOT NULL UNIQUE,FNAC date NOT NULL, PRIMARY KEY(id),FOREIGN KEY (IDMfk) REFERENCES Modulos (id) ON DELETE CASCADE ON UPDATE CASCADE);

SELECT * FROM Alumnos;

SHOW CREATE TABLE Modulos;
