

CREATE DATABASE IF NOT EXISTS BDMULTAS; USE BDMULTAS;
CREATE TABLE PERSONAS (
DNI VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL )ENGINE='INNODB';
CREATE TABLE MATRICULAS (
MATRICULA VARCHAR(10) PRIMARY KEY, DNI VARCHAR(30) NOT NULL,
FOREIGN KEY (DNI) REFERENCES PERSONAS(DNI) )ENGINE='INNODB';
CREATE TABLE MULTAS
(
REF VARCHAR(20) PRIMARY KEY,
MATRICULA VARCHAR(10) NOT NULL,
IMPORTE DECIMAL(6,2) NOT NULL,
LUGAR VARCHAR(30) NOT NULL,
FOREIGN KEY (MATRICULA)REFERENCES MATRICULAS(MATRICULA)
)ENGINE='INNODB';

ALTER TABLE PERSONAS ADD DIRECCION VARCHAR(20) NOT NULL AFTER DIRECCION;

ALTER TABLE PERSONAS MODIFY DIRECCION VARCHAR(20) NOT NULL DEFALUT “DIRECCION PERSONA”;

ALTER TABLE PERSONAS MODIFY DIRECCION VARCHAR(40);

ALTER TABLE PERSONAS ADD FNAC DATE DEFAULT "2000-01-12" AFTER DIRECCION;

ALTER TABLE PERSONAS CHANGE FNAC FECHA_NAC DATE;

ALTER TABLE PERSONAS ADD UNIQUE(NOMBRE);

ALTER TABLE MATRICULAS ADD COLORES ENUM ('rojo', 'azul','blanco');

CREATE TABLE TEMP(CAMPO1 INT, CAMPO2 BOOL, CAMPO3 INT CHECK(CAMPO3>0));

RENAME TABLE TEMP TO AUXILIAR;





